In [1]:
import numpy as np

In [16]:
def sustDelante(L,b):
    n=len(L)
    y=np.empty_like(b)
    y[0] = b[0]/L[0][0]
    for i in range(1,n):
        y[i] = b[i]
        for j in range(0,i):
            y[i] -= L[i][j]*y[j]
        y[i] /= L[i][i]
        
    return y

In [21]:
def sustAtras(U,y):
    n=len(U)
    x=np.empty_like(y)
    x[n-1] = y[n-1]/U[n-1][n-1]
    for i in range(n-2,-1,-1):
        x[i] = y[i]
        for j in range(i+1,n):
            x[i] -= U[i][j]*x[j]
        x[i] /= U[i][i]

    return x

In [22]:
Low=np.array([[-4,-3,1],[0,5,1],[0,0,3]])
b=np.ones(3)

In [24]:
res=sustAtras(Low,b)
res

array([-0.26666667,  0.13333333,  0.33333333])

In [19]:
np.linalg.solve(Low,b)

array([-0.26666667,  0.13333333,  0.33333333])

In [20]:
up= np.array([[1,0,0],[-2,1,0],[-1,3,1]])

In [26]:
res1=sustDelante(up,b)
res1

array([ 1.,  3., -7.])

In [27]:
np.linalg.solve(up,b)

array([ 1.,  3., -7.])